config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :categories

	root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :products, :through => :product_categories
	has_many :product_categories
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :categories, :through => :product_categories
	has_many :product_categories

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base

	belongs_to :category
	belongs_to :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
		if params[:c].present?
    	@products = Product.includes(:categories, :product_categories).where(:categories => { :id => params[:c] })
		else
			@products = Product.includes(:categories, :product_categories)
		end
		respond_to do |format|
			format.html
			format.js
			format.json { render json: @products.collect{|p| p.attributes.merge({"categories" => p.product_categories.collect{|pc| pc.category}})} }
			
		end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for @category, html: { class: "form-horizontal", role: "form" } do |f|
  -if @category.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"

      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/categories/edit.html.haml
.page-header
  = link_to categories_path, class: 'btn btn-default f-right MarTop25' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @category, class: 'btn btn-primary f-right MarTop25' do
    %span.glyphicon.glyphicon-pencil
    Show
  %h1.f-left Editing category
  .clear

= render 'form'

app/views/categories/index.html.haml
.page-header
  %a{:href => new_category_path, class: 'btn btn-primary f-right MarTop25'}
    %span.glyphicon.glyphicon-plus
    New Category
  %h1.f-left Listing categories
  .clear
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th
        %th
        %th

    %tbody
      - @categories.each do |category|
        %tr
          %td= category.name
          %td= link_to 'Show', category
          %td= link_to 'Edit', edit_category_path(category)
          %td= link_to 'Destroy', category, data: { confirm: 'Are you sure?' }, method: :delete

app/views/categories/new.html.haml
.page-header
  = link_to categories_path, class: 'btn btn-default  f-right MarTop25' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1.f-left New category
  .clear

= render 'form'

app/views/categories/show.html.haml
.page-header
  = link_to categories_path, class: 'btn btn-default f-right MarTop25' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_category_path(@category), class: 'btn btn-primary f-right MarTop25' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1.f-left Show category
  .clear
%dl.dl-horizontal
  %dt Name:
  %dd= @category.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title FAASOS Test

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "FAASOS Test", root_path, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{:class => (params[:controller] == "categories") ? "active" : ''}
              %a{href: categories_path} Category
            %li{:class => (params[:controller] == "products") ? "active" : ''}
              %a{href: products_path} Product
            
    
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/products/_form.html.haml
= form_for @product, html: { class: "form-horizontal", role: "form" } do |f|
  -if @product.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"

      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  
  .form-group
    = f.label 'Categories', class: 'col-sm-2 control-label'
    .col-sm-10
      = select_tag "product[category_ids][]", options_from_collection_for_select(Category.all, :id, :name, :selected => f.object.category_ids), :multiple => true, class: 'form-control'
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

  

app/views/products/_products.html.haml
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th Name
      %th Description
      %th Categories
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td
          = product.name
        %td
          = product.description
        %td
          = product.product_categories.collect{|pc| "<a href='/products?c=#{pc.category.id}' data-remote=true>##{pc.category.name}</a>"}.join(", ").html_safe
        %td
          = link_to 'Show', product
        %td
          = link_to 'Edit', edit_product_path(product)
        %td
          = link_to 'Destroy', product, data: { confirm: 'Are you sure?' }, method: :delete

app/views/products/edit.html.haml
.page-header
  = link_to products_path, class: 'btn btn-default f-right MarTop25' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @product, class: 'btn btn-primary f-right MarTop25' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1.f-left Editing product
  .clear

= render 'form'

app/views/products/index.html.haml
.page-header
  %a{href: new_product_path, class: 'btn btn-primary f-right MarTop25'}
    %span.glyphicon.glyphicon-plus
    New Product
  %h1.f-left Listing products
  .clear
= form_tag "/products", :id => "search-frm", :method => "get", :remote => true do 
  %label Categories:
  = select_tag "c", options_for_select(Category.pluck(:name, :id), params[:c]), :prompt => "Select", :id => "cat-filter"
.table-responsive#table-data
  = render "products"



:javascript
  $("#cat-filter").change(function(){
    $("#search-frm").submit();
  });

app/views/products/index.js.haml
$("#table-data").html("#{escape_javascript(render "products")}")

app/views/products/new.html.haml
.page-header
  = link_to products_path, class: 'btn btn-default f-right MarTop25' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1.f-left New product
  .clear
= render 'form'

app/views/products/show.html.haml
.page-header
  = link_to products_path, class: 'btn btn-default f-right MarTop25' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_product_path(@product), class: 'btn btn-primary f-right MarTop25' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1.f-left Show product
  .clear
%dl.dl-horizontal
  %dt Name:
  %dd= @product.name
  %dt Description:
  %dd= @product.description